// app/layout.js
import Header from '../app/components/layouts/Header';
import Footer from '../app/components/layouts/Footer';

import './globals.scss';
import ToastNotification from './components/comman/messages/ToastNotification';

export const metadata = {
  title: "Code Creador",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-background text-foreground flex flex-col min-h-screen">
        <Header />
        <div aria-live="polite">
          <ToastNotification />
        </div>
        <main className="flex-grow min-h-[calc(100vh-240px)]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
